import math, random, pygame
n1 = float(input('Digite um número:'))
print(f'O número {n1} tem a parte inteira {n1:.0f}')
n2 = float(input('O cateto oposto?'))
n3 = float(input('O cateto adjacente?'))
n4 = math.sqrt(math.pow(n2,2) + math.pow(n3,2))
print(f'A cateto oposto é {n2} e cateto adjacente é {n3} então a hipotenusa é {n4}')
n5 = float(input('Digite um ângulo:'))
print(f'O seno desse ângulo é {math.sin(math.radians(n5))} o cosseno é {math.cos(math.radians(n5))} a tangente é {math.tan(math.radians(n5))}')
p1 = str(input('O primeiro nome:'))
p2 = str(input('O segundo nome:'))
p3 = str(input('O terceiro nome:'))
p4 = str(input('O quarto nome:'))
list = [p1,p2,p3,p4]
n6 = random.choice(list)
print(f'o sorteado foi {n6}')
print(random.sample(list, k=4))
pygame.init()
pygame.mixer.music.load('FireFirework36.mp3')
pygame.mixer.music.play()
input()
pygame.event.wait()