nome = str(input('Qual o seu nome?'))
print(nome.upper())
print(nome.lower())
sepa = nome.split()
junto = ''.join(sepa)
print(len(junto),"caracterís")
print(f"O primeiro nome tem {len(sepa[0])}")
number = input('Digite um número:')
milhar = number[0:4]
print(f'milhar: {milhar[0]}',)
print(f'centena: {milhar[1]}')
print(f'dezena: {milhar[2]}')
print(f'unidade: {milhar[3]}')
cidade = input("Diga sua cidade")
print('SANTO' in cidade[0:5].upper())
print("SILVA" in nome.upper())
frase = input('Digite uma frase:')
print(frase.upper().count('A'))
print(frase.upper().find('A'))
print(frase.upper().rfind('A'))
nomecompl = input('Seu nome completo?')
word = nomecompl.split()
print(word[0])
print(word[len(word)-1])